// import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="canonical" href="https://www.bigwigmediadigital.com/" />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="en"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="en-in"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/uae/"
          hrefLang="en-ae"
        />
        <link
          rel="alternate"
          href="https://www.bigwigmediadigital.com/"
          hrefLang="x-default"
        />
        <title>
          BigWig Digital | Result-Driven Digital Marketing Agency in India
        </title>
        <meta
          name="description"
          content="BigWig Digital is a full-service digital marketing agency helping businesses grow with expert SEO, social media marketing, Google Ads, and creative campaigns. Drive traffic, leads, and sales with our proven strategies"
        />
        <meta
          name="google-site-verification"
          content="CQRj6Bls-OQCYgV4ne5XEQJ8-6KlU7L2JfhusyIuiwM"
        />
        {/* JSON-LD FAQ */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "Who can benefit from BigWig Digital’s digital marketing services?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "BigWig Digital’s digital marketing services are perfect for startups, small businesses, and growing brands looking to increase online visibility, leads, and conversions through expert strategies.",
                  },
                },
                // ... add other questions here
              ],
            }),
          }}
        />

        {/* JSON-LD Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "BigWig Digital",
              url: "https://bigwigdigital.in",
              logo: "https://www.bigwigdigital.in/assets/bigwig%20digital%20logo%20(11)-T8_kDtlw.png",
              sameAs: [
                "https://www.facebook.com/bigwigdigital/",
                "https://x.com/bigwig_digital",
                "https://www.instagram.com/bigwigmediadigital/",
                "https://www.youtube.com/@BigwigMediaDigital",
                "https://www.linkedin.com/company/106698073/admin/dashboard/",
                "https://in.pinterest.com/bigwigmediadigital/",
              ],
            }),
          }}
        />

        {/* JSON-LD LocalBusiness */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              name: "BigWig Digital",
              image:
                "https://www.bigwigdigital.in/assets/bigwig%20digital%20logo%20(11)-T8_kDtlw.png",
              url: "https://bigwigdigital.in",
              telephone: "+91 8368573451",
              address: {
                "@type": "PostalAddress",
                streetAddress: "Plot # 2, Sanjay Nagar, Gulabi Bagh",
                addressLocality: "Delhi",
                postalCode: "110007",
                addressCountry: "IN",
              },
              openingHoursSpecification: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                ],
                opens: "11:00",
                closes: "19:30",
              },
            }),
          }}
        />
      </head>
      <body>
        {children}
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2WEBR7ZVN9"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2WEBR7ZVN9');
          `}
        </Script>

        {/* Google Analytics second tag */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-MY747LMT5M"
          strategy="afterInteractive"
        />
        <Script id="google-analytics-2" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-MY747LMT5M');
          `}
        </Script>

        {/* Microsoft Clarity */}
        <Script id="clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r); t.async=1; t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0]; y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "soeh75d1oz");
          `}
        </Script>

        {/* Google Tag Manager */}
        <Script id="gtm" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){
              w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0], j=d.createElement(s), dl=l!='dataLayer'?'&l='+l:'';
              j.async=true; j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
            })(window, document, 'script', 'dataLayer', 'GTM-TMMX5VTN');
          `}
        </Script>
      </body>
    </html>
  );
}
